config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :flats

  resources :flats do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price_per_night, numericality: { only_integer: true, greater_than: 7 }
  validates :number_of_guest, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
# class metaApplicationController < ApplicationController
#   def method_missing method, *args, &block
#     return super method, *args, &block unless false# [:show, :edit, :update, :destroy].include(method)
#     self.class.send(:define_method, method) do
#       puts "nothing"
#     end
#     self.send method, *args, &block
#   end
# end


class FlatsController < ApplicationController # metaApplicationController#
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # def method_missing method, *args, &block
  #   raise
  #   byebug
  #   return super method, *args, &block unless [:show, :edit, :update, :destroy].include(method)
  #   self.class.send(:define_method, method) do
  #     puts "000000000000000000000000000000000000000000000000000000000000"
  #   end
  #   self.send method, *args, &block
  # end

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  # def show
  # end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  # def edit
  #   # set_flat
  #   # raise
  # end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  def search
    @flats = Flat.where("name LIKE '%#{params[:query]}%'")
  end

  private

  def flat_params
    params.require('flat').permit(:name, :address, :description, :price_per_night, :number_of_guest, :picture_url)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <%= simple_form_for flat do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guest %>
    <%= f.input :picture_url %>

    <%= f.submit "Submit if you deeply think it s alright", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "index", flats_path, class: "btn btn-primary" %>
</div>

app/views/flats/edit.html.erb
<h1>Edit</h1>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our flats (<%= @flats.length %>) </h1>

  <div style="display: flex;">
    <div style="flex-grow: 1">
      <%= link_to "add a flat", new_flat_path, class: "btn btn-primary"  %>
    </div>
    <div style="flex-grow: 3">
      <%= form_tag search_flats_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Filter flats"
        %>
      <%= submit_tag "Filter", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-3" style='background-color: rgba(150,150,150, .1); margin:10px;'>

        <img src=<%= flat.picture_url %> alt="" style="display: block; width: 98%; height: 50%;">

        <div>
          <%= flat.name %>

          <%= flat.address %>

          <%= flat.number_of_guest %>
          <%= flat.price_per_night %>
        </div>
          <%= link_to "more details", flat_path(flat) %>
          <%= link_to "edit", edit_flat_path(flat) %>
          <%= link_to "delete", flat_path(flat), data: {
            method: :delete, confirm: "are totaly really sure you want to destroy this flat ?! It may decrease the quality of the building !!"
          }  %>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>New</h1>
<%= render 'form', flat: @flat %>

app/views/flats/search.html.erb
<h1>Filtered flats (<%= @flats.length %>) </h1>

<%= link_to "add a flat", new_flat_path %>

<div class="container row">

  <% @flats.each do |flat| %>
    <div class="col-3" style='background-color: rgba(150,150,150, .1); margin:10px;'>

      <img src=<%= flat.picture_url %> alt="" style="height: 150px; width:150px; display: block;">

      <div>
        <%= flat.name %>

        <%= flat.address %>

        <%= flat.number_of_guest %>
        <%= flat.price_per_night %>
      </div>
        <%= link_to "more details", flat_path(flat) %>
    </div>
  <% end %>
</div>
<%= link_to "index", flats_path, class: "btn btn-primary" %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<h3>Details</h3>

<%= link_to "edit", edit_flat_path(@flat) %>
<img src=<%= @flat.picture_url %> alt="" style="height: 250px; width:350px; display: block;">
<div>
  <%= @flat.name %>
  <%= @flat.description %>
  <%= @flat.address %>
  <%= @flat.number_of_guest %>
  <%= @flat.price_per_night %>
</div>

<%= link_to "index", flats_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>